# GolangCI-Lint config
run:
  timeout: 2m
  tests: true
  issues:
    exclude-dirs:
      - k8s

linters:
  disable-all: true
  enable:
    - unused
    - errcheck
    - gocritic
    - gofmt
    - gosimple
    - misspell
    - prealloc
    - revive
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    # - bodyclose  # Disabled: doesn't detect our custom body closer

linters-settings:
  gocritic:
    enabled-tags:
      - performance
      - diagnostic
      - style
      - experimental
      - opinionated
    disabled-checks:
      - hugeParam
      - rangeValCopy
      - unnamedResult

  gofmt:
    simplify: true

  errcheck:
    check-type-assertions: false
    check-blank: false
