output = "models"
wipe = true
no-tests = true
add-enum-types = true
add-global-variants = true

[psql]
dbname = "building_management"
host = "localhost"        
port = 5432
user = "postgres"
pass = "root"
sslmode = "disable"
schema = "public"         # use "public" unless you explicitly changed it
blacklist = ["migrations", "other"]

