name: Building management CI/CD

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: okeny/building_management
  IMAGE_TAG: latest

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod tidy

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Run tests
        run: go test -v ./...

  docker-build-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: lint-and-test
    environment: oms_interview_env  # 👈 Added to access environment-scoped secrets

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  merge-to-master:
    name: Merge main into master
    runs-on: ubuntu-latest
    needs: docker-build-push
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Try merging main into master
        id: merge
        run: |
          git fetch origin
          git checkout -b master origin/master
          git merge origin/main --no-ff --allow-unrelated-histories -m "Auto-merge main into master" || echo "conflict" > conflict.txt

      - name: Create pull request if conflict
        if: ${{ success() && steps.merge.outcome == 'success' && hashFiles('conflict.txt') != '' }}
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master
          branch: main
          title: "🔀 Auto PR: Merge main into master"
          body: |
            ⚠️ Merge conflict detected in `README.md` or other files.
            This PR was created automatically. Please review and resolve the conflict manually.
          draft: false